BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "wfb-ng"
BBFILE_PATTERN_wfb-ng = "^${LAYERDIR}/"
BBFILE_PRIORITY_wfb-ng = "10"

LAYERDEPENDS_wfb-ng = "core"
LAYERSERIES_COMPAT_wfb-ng = "scarthgap"
